# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/promptable',
                'doc_host': 'https://mye.github.io',
                'git_url': 'https://github.com/mye/promptable',
                'lib_path': 'promptable'},
  'syms': {'promptable.core': {'promptable.core.foo': ('core.html#foo', 'promptable/core.py')}}}
